export const greetings = [
  "Hello...",
  "Hola...",
  "Bonjour...",
  "Ndewo...",
  "Hello...",
  "Bawo ni...",
  "Sannu...",
  "Nǐ hǎo...",
  "Hello...",
  "Namaste...",
  "Konnichiwa...",
];

export const projects = [
  {
    id: 1,
    title: "Ayamiverse",
    description:
      "A UI prototype of a Web3 NFT project, with interactive storyline designed to replicate the core functionalities and visuals of platforms.",
    info: "",
    achievement: "",
    image: "ayamiverse-2.png",
    preview: "https://ayamiverse.netlify.app",
    github: "https://github.com/gabu229/ayamiverse",
    skills: ["Frontend", "NextJS", "GSAP", "TailwindCSS", "Web3.JS"],
  },
  {
    id: 2,
    title: "Ahware",
    description:
      "A non stop growing repository of tech enabled tools, services, products.",
    info: "Ahware began as a vision to simplify access to software solutions for developers, entrepreneurs, and businesses. Its goal was to provide a one-stop hub for discovering tools tailored to solving specific challenges. Throughout the process, I deepened my understanding of how to create content-driven platforms that deliver value while staying visually appealing and easy to navigate.",
    achievement:
      "Building Ahware taught me the importance of clear categorization, audience-focused branding, and commitment to consistency in content creation. The positive feedback from peers and initial users validated the idea and gave me confidence in my ability to balance creative and technical skills.",
    image: "ahware.png",
    preview: "https://ahware-demo.netlify.app",
    github: "https://github.com/gabu229/ahware",
    skills: ["Fullstack", "Firebase", "Supabase", "NextJS", "TailwindCSS"],
  },
  {
    id: 3,
    title: "Deev Editor",
    description:
      "A lightweight, multi-language code editor inspired by VSCode, designed for simplicity and efficiency in editing and managing code on the go.",
    info: "The goal of Deev Editor was to explore creating a niche yet practical code editor tailored to developers needing a minimal yet effective tool. This project challenged my ability to replicate complex software interfaces while prioritizing ease of use and performance.",
    achievement:
      "I gained insights into balancing aesthetic appeal with functionality, especially for tools designed for developer audiences. It also sparked a deeper appreciation for the complexities of building multi-language code editors, paving the way for potential future enhancements.",
    image: "deev.png",
    preview: "https://deev.netlify.app/editor",
    github: "https://github.com/gabu229/deev",
    skills: ["Frontend", "NextJS", "ReactJS", "TailwindCSS", "Framer", "Redux"],
  },
  {
    id: 4,
    title: "Eneftee",
    description:
      "A UI prototype of an NFT marketplace designed to replicate the core functionalities and visuals of leading platforms.",
    info: "",
    achievement: "",
    image: "eneftee.png",
    preview: "https://eneftee.netlify.app",
    github: "https://github.com/gabu229/eneftee",
    skills: [
      "Frontend",
      "NextJS",
      "TailwindCSS",
      "Framer",
      "Swiper.JS",
      "Redux",
    ],
  },
  {
    id: 5,
    title: "Prof. Funke",
    description: "A portfolio website for Professor Olumakaiye Motunrayo",
    info: "",
    achievement: "",
    image: "prof.png",
    preview: "https://mfolumakaiye.com",
    github: "/",
    skills: ["Fullstack", "NextJS", "SEO", "ReactJS", "Framer", "NPM"],
  },
  {
    id: 6,
    title: "Dev Gabriel",
    description: "A portfolio website for Gabriel Orie",
    info: "",
    achievement: "",
    image: "portfolio.png",
    preview: "https://mfolumakaiye.com",
    github: "/",
    skills: ["Fullstack", "NextJS", "SEO", "ReactJS", "Framer", "NPM"],
  },
  {
    id: 7,
    title: "Water Heater Sensor GUI",
    description:
      "A simulation tool for generating realistic sensor data, including ambient temperature, water temperature, predicted temperature, and solar intensity.",
    info: "This project aimed to display sensor generated data over HTTP servers, and model sensor behavior for testing and analytical purposes when a connection to the system cannot be established.",
    achievement:
      "This helped me grasp the intricacies of creating time-dependent data simulations.",
    image: "swh.png",
    preview: "https://swh-client.netlify.app",
    github: "/",
    skills: ["HTML", "TailwindCSS", "Javascript", "DaisyUI", "AJAX"],
  },
  // {
  //   id: 8,
  //   title: "Proofil.io",
  //   description: "A web based drag and drop web page builder for everyone.",
  // info: "",
  // achievement: "",
  // image: "",
  //   preview: "/",
  //   github: "/",
  //   skills: [
  //     "Codeigniter",
  //     "NextJS",
  //     "PHP",
  //     "ReactJS",
  //     "Next-Auth",
  //     "Redux",
  //     "Framer",
  //     "Composer",
  //     "NPM",
  //   ],
  // },
];
